language: go

go:
  - 1.3
  - 1.4
  - tip
  
install:
  - export GOPATH="$HOME/gopath"
  - mkdir -p "$GOPATH/src/sevki.org/"
  - mv "$TRAVIS_BUILD_DIR" "$GOPATH/src/sevki.org/graphql"
  - go get -v -t -d sevki.org/graphql/...

script:
  - go test -v sevki.org/graphql/...
