language: go

go:
  - 1.3
  - 1.4
  - tip
  
install:
  - export GOPATH="$HOME/gopath"
  - mkdir -p "$GOPATH/src/graphql.co/"
  - mv "$TRAVIS_BUILD_DIR" "$GOPATH/src/graphql.co/graphql"
  - go get -v -t -d graphql.co/graphql/...

script:
  - go test -v graphql.co/graphql/...
